### ISSUE TITLE
notifyicon

### ISSUE THREAD

**Issue by RyuZinOh** [Nischall01/EasyTo-Do#1]
NotifyIcon1.Text = "EasyTo_do"
        NotifyIcon1.Icon = New Icon("C:\Users\Nischal\Downloads\compressed\to-do-list (3).ico")
        chnage it some , global icons, or include the icon in project and use them , devs local file path wont support to other's device

**Comment by Nischall01** [comment]
My bad, I put that there for testing and then forgot about it."
